Repository ansible/mkdocs-ansible, pull requests merged in 2024-02, with the labels that each got.

#99 Update Ansible theme to match brand color
  .gitignore
  docs/README.md
  mkdocs.yml
  pyproject.toml
  src/mkdocs_ansible/.overrides/.gitignore
  src/mkdocs_ansible/assets/images/favicon.ico
  src/mkdocs_ansible/assets/images/logo.png
  src/mkdocs_ansible/assets/stylesheets/ansible.css
  src/mkdocs_ansible/main.html
  src/mkdocs_ansible/mkdocs_theme.yml
  tox.ini
Labels: enhancement

#101 Fix release pipeline
  .github/workflows/release.yml
Labels: skip-changelog

#104 Update links color
  src/mkdocs_ansible/assets/stylesheets/ansible.css
Labels: enhancement

#106 Fix asset reference to custom css
  .config/dictionary.txt
  docs/README.md
  docs/guide/contributor-guide.md
  mkdocs.yml
  src/mkdocs_ansible/main.html
Labels: enhancement

#107 Drop test guide
  docs/guide/contributor-guide.md
  mkdocs.yml
Labels: skip-changelog

#108 Update dependencies
  .config/constraints.txt
Labels: skip-changelog, dependencies
